### ISSUE TITLE
Revision 23 de Marzo

### ISSUE THREAD

**Issue by gera-gpz** [J-A-C-E/P2_17100199#1]
Buenas tardes Joven 
Estoy revisando su repositorio hoy 23 de marzo y no tiene las tareas 3 y 4.
Es muy importante que cumpla con los trabajos en tiempo y forma
ya que con eso probablemente calificaré

La Tarea 5 es que confirmen el mensaje que publiqué en Classroom

**Comment by J-A-C-E** [comment]
Buenas noches profe, no me percaté que no se visualizaba la tarea en el Github del explorador ya que los subí en la aplicación de escritorio; las tareas ya las agreguéEl 23 mar. 2020 5:02 p. m., Gerardo Pineda <notifications@github.com> escribió:

Buenas tardes Joven

Estoy revisando su repositorio hoy 23 de marzo y no tiene las tareas 3 y 4.

Es muy importante que cumpla con los trabajos en tiempo y forma

ya que con eso probablemente calificaré

La Tarea 5 es que confirmen el mensaje que publiqué en Classroom

**Comment by gera-gpz** [comment]
OK, ya las revise.

T3: Este formulario era con Bootstrap.
T4: Para la serie le faltó capturar los dos valores inciales.

Calificación 70 para las dos.
